In [1]:
import pandas as pd
import numpy as np

In [2]:
batsman=pd.read_excel('/content/batsman_input.xlsx')

CLEANING BATSMAN SHEET

In [3]:
batsman.head()

,match id,batsman,batsman_id,batsman_dob,batsman_details,is_batsman_captain,is_batsman_keeper,inning,runs,balls_faced,...,bowler_id,bowler_dob,bowler_details,is_bowler_keeper,is_bowler_captain,strike_rate,Fours,Sixes,match_dt,ingestion_timestamp
0,8587795,AJ Fh,37351,1986-11-17,AUS:Right-hand bat:Slow left-arm orthodox:,1,0,2,14,15,...,6718844.0,1997-02-05,AUS:Right-hand bat:Right-arm fast:,0.0,0.0,93.33,1.0,NaN,2021-01-08,2022-03-22 12:43:21
1,8587795,Md Ni,181404,1985-01-01,AFG:Right-hand bat:Right-arm offbreak:,0,0,2,71,41,...,NaN,NaN,NaN,NaN,NaN,173.17,9.0,2.0,2021-01-08,2022-03-22 12:43:21
2,8587795,JW Ws,1635773,1988-08-13,AUS:Right-hand bat:Right-arm medium:,0,0,1,16,13,...,NaN,NaN,NaN,NaN,NaN,123.08,1.0,NaN,2021-01-08,2022-03-22 12:43:21
3,8587795,DR Bs,2170762,1991-04-30,ENG:Right-hand bat:Slow left-arm orthodox:,0,0,1,2,4,...,1905847.0,1991-02-12,AUS:Right-hand bat:Right-arm fast-medium:,0.0,0.0,50.00,NaN,NaN,2021-01-08,2022-03-22 12:43:21
4,8587795,AT Cy,2285051,1991-08-27,AUS:Left-hand bat:None:,1,1,1,42,25,...,1594319.0,1988-12-18,PAK:Left-hand bat:Slow left-arm orthodox:,0.0,0.0,168.00,3.0,3.0,2021-01-08,2022-03-22 12:43:21

In [4]:
batsman.columns

Index(['match id', 'batsman', 'batsman_id', 'batsman_dob', 'batsman_details',
       'is_batsman_captain', 'is_batsman_keeper', 'inning', 'runs',
       'balls_faced', 'over_faced_first', 'wicket kind', 'out_by_bowler',
       'out_by_fielder', 'bowler_id', 'bowler_dob', 'bowler_details',
       'is_bowler_keeper', 'is_bowler_captain', 'strike_rate', 'Fours',
       'Sixes', 'match_dt', 'ingestion_timestamp'],
      dtype='object')

In [5]:
print(batsman.isnull().sum())

match id                   0
batsman                    0
batsman_id                 0
batsman_dob                0
batsman_details            0
is_batsman_captain         0
is_batsman_keeper          0
inning                     0
runs                       0
balls_faced                0
over_faced_first           0
wicket kind             5461
out_by_bowler           5461
out_by_fielder         10927
bowler_id               6507
bowler_dob              6507
bowler_details          6507
is_bowler_keeper        5922
is_bowler_captain       6507
strike_rate                0
Fours                  10464
Sixes                  15684
match_dt                   0
ingestion_timestamp        0
dtype: int64

In [6]:
print(batsman['match id'].nunique())

1732

In [7]:
print(batsman['batsman_id'].nunique())

2063

In [8]:
batsman['bat_mat_ID'] = batsman['match id'].astype(str) + ' ' + batsman['batsman_id'].astype(str)

In [9]:
text_to_num = {
    'zero': 0,
    'one': 1,
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six': 6,
    'seven': 7,
    'eight': 8,
    'nine': 9,
    'ten': 10
}
def text_to_float(val):
    try:
        return float(val)
    except ValueError:
        return float(text_to_num.get(val.lower(), float('nan')))

batsman['Fours']=batsman['Fours'].apply(lambda x:text_to_float(x))
batsman['Fours']=batsman['Fours'].fillna(0).astype(float)
batsman['Fours'].dtypes

dtype('float64')

In [10]:
batsman['Sixes']=batsman['Sixes'].apply(lambda x:text_to_float(x))
batsman['Sixes']=batsman['Sixes'].fillna(0).astype(float)

In [11]:
print(batsman.isnull().sum())

match id                   0
batsman                    0
batsman_id                 0
batsman_dob                0
batsman_details            0
is_batsman_captain         0
is_batsman_keeper          0
inning                     0
runs                       0
balls_faced                0
over_faced_first           0
wicket kind             5461
out_by_bowler           5461
out_by_fielder         10927
bowler_id               6507
bowler_dob              6507
bowler_details          6507
is_bowler_keeper        5922
is_bowler_captain       6507
strike_rate                0
Fours                      0
Sixes                      0
match_dt                   0
ingestion_timestamp        0
bat_mat_ID                 0
dtype: int64

In [12]:
print(batsman['bat_mat_ID'].nunique())

24875

In [13]:
batsman['bat_mat_ID_date'] = batsman['match id'].astype(str) + ' ' + batsman['batsman_id'].astype(str) + ' ' +batsman['match_dt'].astype(str)

In [14]:
batsman = batsman.drop_duplicates(subset='bat_mat_ID')

In [15]:
batsman = batsman.copy()
batsman['Fours'] = batsman['Fours'].fillna(0)

In [16]:
batsman['Sixes'] = batsman['Sixes'].fillna(0)

In [17]:
columns_to_update = [
    'out_by_bowler', 'out_by_fielder', 'bowler_id', 'bowler_dob',
    'bowler_details', 'is_bowler_keeper', 'is_bowler_captain'
]

In [18]:
batsman['wicket kind'].replace(np.nan, None, inplace=True)

In [19]:
for column in columns_to_update:
    batsman.loc[batsman['wicket kind'] == None, column] = None

In [20]:
batsman['is_bowler_captain'].replace(np.nan, None, inplace=True)

In [21]:
batsman['wicket kind'] = batsman['wicket kind'].fillna('Not Out')
batsman['out_by_bowler'] = batsman['out_by_bowler'].fillna('Not Applicable')
batsman['out_by_fielder'] = batsman['out_by_fielder'].fillna('Not Applicable')
batsman['bowler_id'] = batsman['bowler_id'].fillna('Not Applicable')
batsman['bowler_details'] = batsman['bowler_details'].fillna('Not Applicable')
batsman['bowler_dob'] = batsman['bowler_dob'].fillna('Not Applicable')
batsman['is_bowler_keeper'] = batsman['is_bowler_keeper'].fillna(0)
batsman['is_bowler_captain'] = batsman['is_bowler_captain'].fillna(0)

In [22]:
print(batsman.isnull().sum())

match id               0
batsman                0
batsman_id             0
batsman_dob            0
batsman_details        0
is_batsman_captain     0
is_batsman_keeper      0
inning                 0
runs                   0
balls_faced            0
over_faced_first       0
wicket kind            0
out_by_bowler          0
out_by_fielder         0
bowler_id              0
bowler_dob             0
bowler_details         0
is_bowler_keeper       0
is_bowler_captain      0
strike_rate            0
Fours                  0
Sixes                  0
match_dt               0
ingestion_timestamp    0
bat_mat_ID             0
bat_mat_ID_date        0
dtype: int64

In [23]:
batsman = batsman.drop(columns=['bat_mat_ID', 'bat_mat_ID_date'])

SAVING THE CLEANED BATSMAN SHEET

In [24]:
batsman.to_excel(
    "Batsmancleaned.xlsx",
    sheet_name='Batsman_Scorecard',
    index=False,
    startrow=1,
    startcol=1
)

CALCULATING TOTAL POINTS FOR EACH BATSMAN BASED ON STRIKE RATE,AVERAGE OF RUNS,100S AND 50S

In [25]:
# Convert necessary columns to numeric or datetime format
batsman['runs'] = pd.to_numeric(batsman['runs'], errors='coerce')
batsman['runs'] = batsman['runs'].fillna(0)
batsman['strike_rate'] = pd.to_numeric(batsman['strike_rate'], errors='coerce')
batsman['strike_rate'] = batsman['strike_rate'].fillna(0)
batsman['match_dt'] = pd.to_datetime(batsman['match_dt'], errors='coerce')

In [26]:
# Calculate the total runs for each batsman
total_runs = batsman.groupby(['batsman_id', 'batsman'])['runs'].sum().reset_index()
total_runs.columns = ['batsman_id', 'batsman', 'total_runs']

In [27]:
#strike rate
batsman_strike_rate = batsman.groupby(['batsman_id','batsman'])['strike_rate'].mean().reset_index()

In [28]:
batsman_strike_rate

      batsman_id batsman  strike_rate
0          31464   DG Be    40.910000
1          34061   DT Cn   119.160577
2          36665   CJ Fn    99.854000
3          37351   AJ Fh   101.781692
4          41740   MC Hs   116.654878
...          ...     ...          ...
2058     9822322   Sv Dy     0.000000
2059     9822392   PR Vr     0.000000
2060     9874052   BJ Js   210.000000
2061     9883250    T Si    80.000000
2062     9899140    S Ua    40.000000

[2063 rows x 3 columns]

In [29]:
# Calculating the average runs for each batsman
average_runs = batsman.groupby(['batsman_id', 'batsman'])['runs'].mean().reset_index()
average_runs.columns = ['batsman_id', 'batsman', 'average_runs']

In [30]:
# Calculating the number of centuries and half-centuries
centuries = batsman[batsman['runs'] >= 100].groupby(['batsman_id', 'batsman']).size().reset_index(name='centuries')
half_centuries = batsman[(batsman['runs'] >= 50) & (batsman['runs'] < 100)].groupby(['batsman_id', 'batsman']).size().reset_index(name='half_centuries')

In [31]:
# Merging
metrics = pd.merge(total_runs, average_runs, on=['batsman_id', 'batsman'])
metrics = pd.merge(metrics, centuries, on=['batsman_id', 'batsman'], how='left').fillna(0)
metrics = pd.merge(metrics, half_centuries, on=['batsman_id', 'batsman'], how='left').fillna(0)
metrics=pd.merge(metrics,batsman_strike_rate,on=['batsman_id','batsman'],how='left').fillna(0)

In [32]:
#defining functions to allot points according to the point system

# Function to calculate points based on the strike rate
def strike_rate_points(sr):
    if sr >= 150:
        return 50
    elif sr >= 100:
        return 40
    elif sr >= 80:
        return 30
    else:
        return 0

# Function to calculate points based on the average runs
def average_points(avg):
    if avg >= 50:
        return 30
    elif avg >= 40:
        return 20
    elif avg >= 30:
        return 10
    else:
        return 5

# Function to calculate points for centuries
def centuries_points(cent):
    if cent >= 3:
        return 30
    elif cent == 2:
        return 20
    elif cent == 1:
        return 10
    else:
        return 0

# Function to calculate points for half-centuries
def half_centuries_points(hc):
    if hc >= 5:
        return 20
    elif hc >= 3:
        return 10
    elif hc >= 1:
        return 5
    else:
        return 0

In [33]:
#applying points
batsman_strike_rate['strike_rate_points'] = batsman_strike_rate['strike_rate'].apply(strike_rate_points)
metrics = pd.merge(metrics, batsman_strike_rate[['batsman_id', 'strike_rate_points']], on='batsman_id', how='left')

In [34]:
#applying points
metrics['average_points'] = metrics['average_runs'].apply(average_points)
metrics['centuries_points'] = metrics['centuries'].apply(centuries_points)
metrics['half_centuries_points'] = metrics['half_centuries'].apply(half_centuries_points)

In [35]:
# Calculating the total points
metrics['total_points'] = (metrics['strike_rate_points'] + metrics['average_points'] +
                           metrics['centuries_points'] + metrics['half_centuries_points'])

In [36]:
metrics.head()

,batsman_id,batsman,total_runs,average_runs,centuries,half_centuries,strike_rate,strike_rate_points,average_points,centuries_points,half_centuries_points,total_points
0,31464,DG Be,10,3.333333,0.0,0.0,40.910000,0,5,0,0,5
1,34061,DT Cn,729,14.019231,0.0,2.0,119.160577,40,5,0,5,50
2,36665,CJ Fn,208,20.800000,0.0,0.0,99.854000,30,5,0,0,35
3,37351,AJ Fh,1517,23.338462,0.0,12.0,101.781692,40,5,0,20,65
4,41740,MC Hs,976,23.804878,0.0,6.0,116.654878,40,5,0,20,65

PRINTING SHEET CONTANING TOTAL POINTS OF ALL BATSMAN

In [37]:
metrics.to_excel(
    "batsmantotalpoints.xlsx",
    sheet_name='Batsman_totalpoints',
    index=False,
    startrow=1,
    startcol=1
)

CALCULATING PERFORMANCE SCORE OF PLAYERS

In [38]:
batsman_cumulative_runs = batsman.groupby('batsman_id').agg(
    cumulative_runs=pd.NamedAgg(column='runs', aggfunc='sum')
).reset_index()

In [39]:
batsman_cumulative_runs

      batsman_id  cumulative_runs
0          31464               10
1          34061              729
2          36665              208
3          37351             1517
4          41740              976
...          ...              ...
2058     9822322                0
2059     9822392                0
2060     9874052               42
2061     9883250               20
2062     9899140                4

[2063 rows x 2 columns]

In [40]:
#normalizing runs for meaningful comparisons
min_run =batsman_cumulative_runs['cumulative_runs'].min()
max_run = batsman_cumulative_runs['cumulative_runs'].max()

In [41]:
batsman_cumulative_runs['normalized_runs'] = 1 + ((batsman_cumulative_runs['cumulative_runs'] - min_run) * (100 - 1) / (max_run - min_run))

In [42]:
batsman_cumulative_runs

      batsman_id  cumulative_runs  normalized_runs
0          31464               10         1.245597
1          34061              729        18.903994
2          36665              208         6.108410
3          37351             1517        38.257008
4          41740              976        24.970231
...          ...              ...              ...
2058     9822322                0         1.000000
2059     9822392                0         1.000000
2060     9874052               42         2.031506
2061     9883250               20         1.491193
2062     9899140                4         1.098239

[2063 rows x 3 columns]

In [43]:
batsman_data = batsman_cumulative_runs.merge(
    batsman[['batsman_id','runs', 'match_dt','bowler_id']],
    on='batsman_id',
    how='left'
)

Consistency:

Low Standard Deviation: This suggests that the batsman is consistent in their performance, regularly scoring around the same number of runs.

High Standard Deviation:  This suggests inconsistency, where the batsman may have very high scores in some matches and very low scores in others.

In [44]:
batsman_std = batsman_data.groupby('batsman_id').agg(
    std=pd.NamedAgg(column='runs', aggfunc=np.std)
).reset_index()

In [45]:
batsman_std

      batsman_id        std
0          31464   4.163332
1          34061  15.309219
2          36665  16.824585
3          37351  22.687605
4          41740  21.220532
...          ...        ...
2058     9822322        NaN
2059     9822392        NaN
2060     9874052        NaN
2061     9883250        NaN
2062     9899140        NaN

[2063 rows x 2 columns]

In [46]:
batsman_std['inverse_std'] = batsman_std['std'].apply(lambda x: 1 / x if x != 0 else np.inf)

In [47]:
batsman_std.rename(columns={'inverse_std': 'consistency'}, inplace=True)

In [48]:
batsman_std

      batsman_id        std  consistency
0          31464   4.163332     0.240192
1          34061  15.309219     0.065320
2          36665  16.824585     0.059437
3          37351  22.687605     0.044077
4          41740  21.220532     0.047124
...          ...        ...          ...
2058     9822322        NaN          NaN
2059     9822392        NaN          NaN
2060     9874052        NaN          NaN
2061     9883250        NaN          NaN
2062     9899140        NaN          NaN

[2063 rows x 3 columns]

In [49]:
min_consistency = batsman_std['consistency'].min()
max_consistency = batsman_std['consistency'].max()

In [50]:
batsman_std['normalized_consistency'] = 1 + ((batsman_std['consistency'] - min_consistency) * (100 - 1) / (max_consistency - min_consistency))

print(batsman_std)

      batsman_id        std  consistency  normalized_consistency
0          31464   4.163332     0.240192                     1.0
1          34061  15.309219     0.065320                     1.0
2          36665  16.824585     0.059437                     1.0
3          37351  22.687605     0.044077                     1.0
4          41740  21.220532     0.047124                     1.0
...          ...        ...          ...                     ...
2058     9822322        NaN          NaN                     NaN
2059     9822392        NaN          NaN                     NaN
2060     9874052        NaN          NaN                     NaN
2061     9883250        NaN          NaN                     NaN
2062     9899140        NaN          NaN                     NaN

[2063 rows x 4 columns]

RECENCY

Here we are using 'calculate_recency' function to calculates a weighted average of a batsman's runs, giving more weight to recent matches. This helps assess the batsman's current form by emphasizing recent performances over older ones.

In [51]:
def calculate_recency(group):
    group = group.sort_values('match_dt')
    decay_rate = 0.1

    group['match_dt'] = pd.to_datetime(group['match_dt'])
    time_diff = (group['match_dt'].max() - group['match_dt']).dt.days
    weights = np.exp(-decay_rate * time_diff)
    return np.average(group['runs'], weights=weights)

batsman_recency = batsman_data.groupby('batsman_id').apply(calculate_recency).reset_index(name='recency')

In [52]:
min_recency = batsman_recency['recency'].min()
max_recency = batsman_recency['recency'].max()

In [53]:
batsman_recency['normalized_recency'] = 1 + ((batsman_recency['recency'] - min_recency) * (100 - 1) / (max_recency - min_recency))

print(batsman_recency)

      batsman_id    recency  normalized_recency
0          31464   2.955211            3.925664
1          34061   6.110932            7.049833
2          36665  27.429023           28.154779
3          37351  17.945186           18.765765
4          41740   5.000000            5.950009
...          ...        ...                 ...
2058     9822322   0.000000            1.000000
2059     9822392   0.000000            1.000000
2060     9874052  42.000000           42.580072
2061     9883250  20.000000           20.800034
2062     9899140   4.000000            4.960007

[2063 rows x 3 columns]

In [54]:
batsman_performance = batsman_cumulative_runs.merge(
    batsman_std, on='batsman_id'
).merge(
    batsman_recency, on='batsman_id'
)

In [55]:
batsman_performance

,batsman_id,cumulative_runs,normalized_runs,std,consistency,normalized_consistency,recency,normalized_recency
0,31464,10,1.245597,4.163332,0.240192,1.0,2.955211,3.925664
1,34061,729,18.903994,15.309219,0.065320,1.0,6.110932,7.049833
2,36665,208,6.108410,16.824585,0.059437,1.0,27.429023,28.154779
3,37351,1517,38.257008,22.687605,0.044077,1.0,17.945186,18.765765
4,41740,976,24.970231,21.220532,0.047124,1.0,5.000000,5.950009
...,...,...,...,...,...,...,...,...
2058,9822322,0,1.000000,NaN,NaN,NaN,0.000000,1.000000
2059,9822392,0,1.000000,NaN,NaN,NaN,0.000000,1.000000
2060,9874052,42,2.031506,NaN,NaN,NaN,42.000000,42.580072
2061,9883250,20,1.491193,NaN,NaN,NaN,20.000000,20.800034
2062,9899140,4,1.098239,NaN,NaN,NaN,4.000000,4.960007

In [56]:
batsman_performance['performance_score'] = (
    0.5 * batsman_performance['normalized_runs'] +
    0.3 * (batsman_performance['normalized_consistency'].fillna(0)) +
    0.2 * batsman_performance['normalized_recency']
)

In [57]:
batsman_performance

,batsman_id,cumulative_runs,normalized_runs,std,consistency,normalized_consistency,recency,normalized_recency,performance_score
0,31464,10,1.245597,4.163332,0.240192,1.0,2.955211,3.925664,1.707931
1,34061,729,18.903994,15.309219,0.065320,1.0,6.110932,7.049833,11.161964
2,36665,208,6.108410,16.824585,0.059437,1.0,27.429023,28.154779,8.985161
3,37351,1517,38.257008,22.687605,0.044077,1.0,17.945186,18.765765,23.181657
4,41740,976,24.970231,21.220532,0.047124,1.0,5.000000,5.950009,13.975117
...,...,...,...,...,...,...,...,...,...
2058,9822322,0,1.000000,NaN,NaN,NaN,0.000000,1.000000,0.700000
2059,9822392,0,1.000000,NaN,NaN,NaN,0.000000,1.000000,0.700000
2060,9874052,42,2.031506,NaN,NaN,NaN,42.000000,42.580072,9.531767
2061,9883250,20,1.491193,NaN,NaN,NaN,20.000000,20.800034,4.905603
2062,9899140,4,1.098239,NaN,NaN,NaN,4.000000,4.960007,1.541121

In [58]:
batsman_performance.columns

Index(['batsman_id', 'cumulative_runs', 'normalized_runs', 'std',
       'consistency', 'normalized_consistency', 'recency',
       'normalized_recency', 'performance_score'],
      dtype='object')

Now we have the performance score and the total points based on scoring system for all batsman thus we can calculate the final score by adding these two values

In [59]:
merged_batsman = pd.merge(metrics, batsman_performance, on='batsman_id')

In [60]:
merged_batsman

,batsman_id,batsman,total_runs,average_runs,centuries,half_centuries,strike_rate,strike_rate_points,average_points,centuries_points,half_centuries_points,total_points,cumulative_runs,normalized_runs,std,consistency,normalized_consistency,recency,normalized_recency,performance_score
0,31464,DG Be,10,3.333333,0.0,0.0,40.910000,0,5,0,0,5,10,1.245597,4.163332,0.240192,1.0,2.955211,3.925664,1.707931
1,34061,DT Cn,729,14.019231,0.0,2.0,119.160577,40,5,0,5,50,729,18.903994,15.309219,0.065320,1.0,6.110932,7.049833,11.161964
2,36665,CJ Fn,208,20.800000,0.0,0.0,99.854000,30,5,0,0,35,208,6.108410,16.824585,0.059437,1.0,27.429023,28.154779,8.985161
3,37351,AJ Fh,1517,23.338462,0.0,12.0,101.781692,40,5,0,20,65,1517,38.257008,22.687605,0.044077,1.0,17.945186,18.765765,23.181657
4,41740,MC Hs,976,23.804878,0.0,6.0,116.654878,40,5,0,20,65,976,24.970231,21.220532,0.047124,1.0,5.000000,5.950009,13.975117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2058,9822322,Sv Dy,0,0.000000,0.0,0.0,0.000000,0,5,0,0,5,0,1.000000,NaN,NaN,NaN,0.000000,1.000000,0.700000
2059,9822392,PR Vr,0,0.000000,0.0,0.0,0.000000,0,5,0,0,5,0,1.000000,NaN,NaN,NaN,0.000000,1.000000,0.700000
2060,9874052,BJ Js,42,42.000000,0.0,0.0,210.000000,50,20,0,0,70,42,2.031506,NaN,NaN,NaN,42.000000,42.580072,9.531767
2061,9883250,T Si,20,20.000000,0.0,0.0,80.000000,30,5,0,0,35,20,1.491193,NaN,NaN,NaN,20.000000,20.800034,4.905603
2062,9899140,S Ua,4,4.000000,0.0,0.0,40.000000,0,5,0,0,5,4,1.098239,NaN,NaN,NaN,4.000000,4.960007,1.541121

In [61]:
merged_batsman.columns

Index(['batsman_id', 'batsman', 'total_runs', 'average_runs', 'centuries',
       'half_centuries', 'strike_rate', 'strike_rate_points', 'average_points',
       'centuries_points', 'half_centuries_points', 'total_points',
       'cumulative_runs', 'normalized_runs', 'std', 'consistency',
       'normalized_consistency', 'recency', 'normalized_recency',
       'performance_score'],
      dtype='object')

In [62]:
merged_batsman['final_score'] = merged_batsman['performance_score'] + merged_batsman['total_points']

In [63]:
final_batsman = merged_batsman[['batsman_id','batsman','total_runs','average_runs','centuries',
       'half_centuries','strike_rate','strike_rate_points','average_points',
       'centuries_points','half_centuries_points','performance_score','total_points','final_score']]

In [64]:
final_batsman

,batsman_id,batsman,total_runs,average_runs,centuries,half_centuries,strike_rate,strike_rate_points,average_points,centuries_points,half_centuries_points,performance_score,total_points,final_score
0,31464,DG Be,10,3.333333,0.0,0.0,40.910000,0,5,0,0,1.707931,5,6.707931
1,34061,DT Cn,729,14.019231,0.0,2.0,119.160577,40,5,0,5,11.161964,50,61.161964
2,36665,CJ Fn,208,20.800000,0.0,0.0,99.854000,30,5,0,0,8.985161,35,43.985161
3,37351,AJ Fh,1517,23.338462,0.0,12.0,101.781692,40,5,0,20,23.181657,65,88.181657
4,41740,MC Hs,976,23.804878,0.0,6.0,116.654878,40,5,0,20,13.975117,65,78.975117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2058,9822322,Sv Dy,0,0.000000,0.0,0.0,0.000000,0,5,0,0,0.700000,5,5.700000
2059,9822392,PR Vr,0,0.000000,0.0,0.0,0.000000,0,5,0,0,0.700000,5,5.700000
2060,9874052,BJ Js,42,42.000000,0.0,0.0,210.000000,50,20,0,0,9.531767,70,79.531767
2061,9883250,T Si,20,20.000000,0.0,0.0,80.000000,30,5,0,0,4.905603,35,39.905603
2062,9899140,S Ua,4,4.000000,0.0,0.0,40.000000,0,5,0,0,1.541121,5,6.541121

In [65]:
#coverting the sheet we have containing final score into excel
final_batsman.to_excel('final_batsman_scores.xlsx', index=False)

Now filtering batsman with runs>100 according to the criteria given to us

In [66]:
batsman_cumulative_runs = batsman.groupby('batsman_id').agg(
    cumulative_runs=pd.NamedAgg(column='runs', aggfunc='sum')
).reset_index()

In [67]:
#putting filter for runs more than 100
batsman_above100 = batsman_cumulative_runs[batsman_cumulative_runs['cumulative_runs'] > 100]

print(batsman_above100)

      batsman_id  cumulative_runs
1          34061              729
2          36665              208
3          37351             1517
4          41740              976
5          46794              564
...          ...              ...
1974     9009265              111
1983     9036516              331
1987     9047499              162
2001     9098571              124
2022     9320597              143

[786 rows x 2 columns]

In [68]:
batsmanover100 = pd.merge(batsman_above100,final_batsman , on='batsman_id')

In [69]:
batsmanover100

,batsman_id,cumulative_runs,batsman,total_runs,average_runs,centuries,half_centuries,strike_rate,strike_rate_points,average_points,centuries_points,half_centuries_points,performance_score,total_points,final_score
0,34061,729,DT Cn,729,14.019231,0.0,2.0,119.160577,40,5,0,5,11.161964,50,61.161964
1,36665,208,CJ Fn,208,20.800000,0.0,0.0,99.854000,30,5,0,0,8.985161,35,43.985161
2,37351,1517,AJ Fh,1517,23.338462,0.0,12.0,101.781692,40,5,0,20,23.181657,65,88.181657
3,41740,976,MC Hs,976,23.804878,0.0,6.0,116.654878,40,5,0,20,13.975117,65,78.975117
4,46794,564,SE Mh,564,35.250000,0.0,6.0,111.088750,40,10,0,20,19.039146,70,89.039146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,9009265,111,Jy Gl,111,15.857143,0.0,0.0,133.374286,40,5,0,0,9.327777,45,54.327777
782,9036516,331,TB Rn,331,27.583333,1.0,1.0,104.068333,40,5,10,5,18.165818,60,78.165818
783,9047499,162,YV Dl,162,23.142857,0.0,0.0,78.822857,0,5,0,0,7.780311,5,12.780311
784,9098571,124,Tg Gl,124,24.800000,0.0,2.0,148.110000,40,5,0,5,9.964389,50,59.964389
785,9320597,143,Ma Bg,143,17.875000,0.0,0.0,105.963750,40,5,0,0,6.458507,45,51.458507

Sorting over100 based on performance score first and then on total points.later we will find the common between the two so we can get batsman with better total points as well as performance score.

In [70]:
a=batsmanover100.sort_values(by='performance_score', ascending=False).head(20)
print(a)

     batsman_id  cumulative_runs  batsman  total_runs  average_runs  \
180     2263736             4031    Md Rn        4031     43.815217
164     2162782             3498    JC Br        3498     36.061856
482     4685568             2525    PD St        2525     24.047619
139     2076192             2984    JM Ve        2984     31.410526
102     1749075             3203    AD Hs        3203     28.598214
46       313809             2798  F du Ps        2798     33.309524
290     3125562             2551    SA Yv        2551     31.887500
256     2827327             2678    LS Le        2678     27.050505
632     6818622             1586    Rh Gz        1586     25.174603
85      1626526             2737     C Mo        2737     30.411111
183     2275195             2480    GJ Ml        2480     26.105263
229     2654014             2693  Q de Kk        2693     29.593407
212     2437021             2720    Br Am        2720     33.170732
228     2653993             2552    DP Cy        2552     34.026667
145     2089079             2608    JJ Ry        2608     28.043011
187     2286472             1772    CA Ln        1772     31.087719
650     7422673             1975    RD Gd        1975     35.267857
104     1776627             1779     V Ki        1779     31.210526
624     6718326             2280    FH An        2280     27.142857
177     2252452             2201    DA Mr        2201     23.414894

     centuries  half_centuries  strike_rate  strike_rate_points  \
180        2.0            38.0   115.673261                  40
164        6.0            26.0   123.307835                  40
482        1.0            14.0   132.002952                  40
139        1.0            21.0   116.674421                  40
102        3.0            20.0   130.018214                  40
46         3.0            20.0   114.388095                  40
290        4.0            19.0   136.978500                  40
256        1.0            16.0   140.219192                  40
632        1.0             9.0   126.020635                  40
85         1.0            17.0   127.727889                  40
183        3.0            14.0   126.458211                  40
229        2.0            20.0   121.033846                  40
212        2.0            25.0   107.100854                  40
228        0.0            21.0   108.051733                  40
145        2.0            16.0   120.069355                  40
187        1.0            14.0   132.004211                  40
650        2.0            14.0   116.248571                  40
104        1.0            17.0   104.569123                  40
624        0.0            16.0   146.266071                  40
177        1.0            10.0   130.615638                  40

     average_points  centuries_points  half_centuries_points  \
180              20                20                     20
164              10                30                     20
482               5                10                     20
139              10                10                     20
102               5                30                     20
46               10                30                     20
290              10                30                     20
256               5                10                     20
632               5                10                     20
85               10                10                     20
183               5                30                     20
229               5                20                     20
212              10                20                     20
228              10                 0                     20
145               5                20                     20
187              10                10                     20
650              10                20                     20
104              10                10                     20
624               5                 0                     20
177               5                10                     20

     performance_score  total_points  final_score
180          61.356321           100   161.356321
164          50.054794           100   150.054794
482          46.750240            75   121.750240
139          45.186521            80   125.186521
102          44.560658            95   139.560658
46           44.175756           100   144.175756
290          43.782509           100   143.782509
256          41.746670            75   116.746670
632          40.275812            75   115.275812
85           38.932184            80   118.932184
183          36.817674            95   131.817674
229          36.808932            85   121.808932
212          36.806380            90   126.806380
228          36.437290            70   106.437290
145          35.552720            85   120.552720
187          35.188146            80   115.188146
650          34.711445            90   124.711445
104          34.605536            80   114.605536
624          33.668220            65    98.668220
177          33.353509            75   108.353509

In [71]:
batsmanover100.to_excel('over100runsbatsmanscore.xlsx', index=False)

In [72]:
a.to_excel('top_sortedbatsman.xlsx', index=False)

NOW WE WILL BE DEALING WITH THE BOWLER SHEET

In [73]:
bowler=pd.read_excel('/content/bowler_input.xlsx')

CHECKING FOR NULLS AND DUPLICATES

In [74]:
bowler.head()

,match id,bowler,bowler_id,bowler_dob,bowler_details,is_bowler_captain,is_bowler_keeper,inning,runs,wicket_count,balls_bowled,economy,maiden,dots,Fours,Sixes,wides,noballs,match_dt,ingestion_timestamp
0,8587795,PM Se,55299,1984-11-25,AUS:Right-hand bat:Right-arm fast-medium:,0,0,2,38,0,24,9.50,0,8,4,1,1,0,2021-01-08,2022-03-21 03:44:58
1,8587795,Md Ni,181404,1985-01-01,AFG:Right-hand bat:Right-arm offbreak:,0,0,1,9,0,6,9.00,0,1,1,0,0,0,2021-01-08,2022-03-21 03:44:58
2,8587795,Id Wm,1594319,1988-12-18,PAK:Left-hand bat:Slow left-arm orthodox:,0,0,1,28,1,24,7.00,0,6,3,0,0,0,2021-01-08,2022-03-21 03:44:58
3,8587795,KW Rn,1905847,1991-02-12,AUS:Right-hand bat:Right-arm fast-medium:,0,0,1,40,1,24,10.00,0,10,2,3,3,0,2021-01-08,2022-03-21 03:44:58
4,8587795,DR Bs,2170762,1991-04-30,ENG:Right-hand bat:Slow left-arm orthodox:,0,0,2,37,1,24,9.25,0,7,4,1,0,0,2021-01-08,2022-03-21 03:44:58

In [75]:
bowler.columns

Index(['match id', 'bowler', 'bowler_id', 'bowler_dob', 'bowler_details',
       'is_bowler_captain', 'is_bowler_keeper', 'inning', 'runs',
       'wicket_count', 'balls_bowled', 'economy', 'maiden', 'dots', 'Fours',
       'Sixes', 'wides', 'noballs', 'match_dt', 'ingestion_timestamp'],
      dtype='object')

In [76]:
print(bowler.isnull().sum())

match id               0
bowler                 0
bowler_id              0
bowler_dob             0
bowler_details         0
is_bowler_captain      0
is_bowler_keeper       0
inning                 0
runs                   0
wicket_count           0
balls_bowled           0
economy                0
maiden                 0
dots                   0
Fours                  0
Sixes                  0
wides                  0
noballs                0
match_dt               0
ingestion_timestamp    0
dtype: int64

In [77]:
duplicates = bowler[bowler.duplicated()]
print(duplicates)

Empty DataFrame
Columns: [match id, bowler, bowler_id, bowler_dob, bowler_details, is_bowler_captain, is_bowler_keeper, inning, runs, wicket_count, balls_bowled, economy, maiden, dots, Fours, Sixes, wides, noballs, match_dt, ingestion_timestamp]
Index: []

In [78]:
bowler['bowler_id'].nunique()

1511

SINCE MOST OF THE DATA IS ALREADY CLEANED AND I ALSO CHECKED IN EXCEL NOW PROCEEDING TO CALCULATE THEIR SCORES BASED ON STRIKE RATE OF BOWLERS,ECONOMY(ALREADY GIVEN IN DATA),BOWLING AVERAGE AND WICKETS PER INNINGS.

In [79]:
#calculating total balls bowled and total wickets taken
total_ballsbowled = bowler.groupby('bowler_id')['balls_bowled'].sum()
total_wickets = bowler.groupby('bowler_id')['wicket_count'].sum()

In [80]:
# Computing strike rate for each bowler
bowler_strike_rate = (total_ballsbowled / total_wickets).reset_index()
bowler_strike_rate.columns = ['bowler_id', 'strike_rate']
bowler_strike_rate['strike_rate'].replace([np.inf, -np.inf], np.nan, inplace=True)
print(bowler_strike_rate)

      bowler_id  strike_rate
0         34061    23.518519
1         41740    18.000000
2         49496    16.645161
3         55299    15.413043
4         62432    16.361111
...         ...          ...
1506    9822322          NaN
1507    9822392     6.000000
1508    9822420    12.000000
1509    9822441    12.000000
1510    9888584    12.000000

[1511 rows x 2 columns]

In [81]:
#average economy
bowler_economy= bowler.groupby(['bowler_id', 'bowler'])['economy'].mean().reset_index()

In [82]:
bowler_economy

      bowler_id bowler    economy
0         34061  DT Cn   9.490000
1         41740  MC Hs   5.900000
2         49496  SJ Oe   6.203043
3         55299  PM Se   8.097429
4         62432  MM Ai   7.826494
...         ...    ...        ...
1506    9822322  Sv Dy   7.250000
1507    9822392  PR Vr   2.330000
1508    9822420  PS Pa  17.000000
1509    9822441   K Ta  14.250000
1510    9888584  NS Pa  11.500000

[1511 rows x 3 columns]

  We are not clearly given the runs conceded so we can calculate it by the formula of economy.

In [83]:
bowler['runs_conceded'] = bowler['economy'] * bowler['balls_bowled'] / 6
print(bowler[['bowler_id', 'bowler', 'balls_bowled', 'economy', 'runs_conceded']])

       bowler_id    bowler  balls_bowled  economy  runs_conceded
0          55299     PM Se            24     9.50          38.00
1         181404     Md Ni             6     9.00           9.00
2        1594319     Id Wm            24     7.00          28.00
3        1905847     KW Rn            24    10.00          40.00
4        2170762     DR Bs            24     9.25          37.00
...          ...       ...           ...      ...            ...
18856    8463783     Bl Hd             6    17.00          17.00
18857    8489816     Ai Nr            24     8.00          32.00
18858    8688868  An Al Kn            24     6.50          26.00
18859    8688973     Nh Ki            18    14.67          44.01
18860    9471244     Md Jh            24     9.00          36.00

[18861 rows x 5 columns]

In [84]:
total_runs_conceded = bowler.groupby('bowler_id')['runs_conceded'].sum()
total_wickets = bowler.groupby('bowler_id')['wicket_count'].sum()

In [85]:
#calculating average
bowler_average = (total_runs_conceded / total_wickets).reset_index()
bowler_average.columns = ['bowler_id', 'bowler_average']
bowler_average['bowler_average'].replace([np.inf, -np.inf], np.nan, inplace=True)
print(bowler_average)

      bowler_id  bowler_average
0         34061       35.741481
1         41740       15.200000
2         49496       17.193871
3         55299       21.261667
4         62432       19.694769
...         ...             ...
1506    9822322             NaN
1507    9822392        2.330000
1508    9822420       34.000000
1509    9822441       28.500000
1510    9888584       23.000000

[1511 rows x 2 columns]

In [86]:
#Calculating 4W_Per_Innings
wickets_4w = bowler[bowler['wicket_count'] >= 4]

# Group by bowler and count the number of innings with 4 or more wickets
four_w_per_innings = wickets_4w.groupby('bowler_id').size().reset_index(name='4W_Per_Innings')

In [87]:
four_w_per_innings

     bowler_id  4W_Per_Innings
0        49496               3
1        55299               1
2        62432               1
3        65183               1
4        74087               1
..         ...             ...
276    8907338               1
277    8986193               2
278    9382967               1
279    9410876               1
280    9455557               2

[281 rows x 2 columns]

In [88]:
bowler_score_df = pd.merge(bowler_strike_rate, bowler_economy, on=['bowler_id'], how='outer')
bowler_score_df = pd.merge(bowler_score_df, bowler_average, on=['bowler_id'], how='outer')
bowler_score_df = pd.merge(bowler_score_df, four_w_per_innings, on=['bowler_id'], how='outer')

In [89]:
bowler_score_df

      bowler_id  strike_rate bowler    economy  bowler_average  4W_Per_Innings
0         34061    23.518519  DT Cn   9.490000       35.741481             NaN
1         41740    18.000000  MC Hs   5.900000       15.200000             NaN
2         49496    16.645161  SJ Oe   6.203043       17.193871             3.0
3         55299    15.413043  PM Se   8.097429       21.261667             1.0
4         62432    16.361111  MM Ai   7.826494       19.694769             1.0
...         ...          ...    ...        ...             ...             ...
1506    9822322          NaN  Sv Dy   7.250000             NaN             NaN
1507    9822392     6.000000  PR Vr   2.330000        2.330000             NaN
1508    9822420    12.000000  PS Pa  17.000000       34.000000             NaN
1509    9822441    12.000000   K Ta  14.250000       28.500000             NaN
1510    9888584    12.000000  NS Pa  11.500000       23.000000             NaN

[1511 rows x 6 columns]

In [90]:
#Giving them points based on the given criteria
# Function to calculate points based on the strike rate
def strike_rate_points(sr):
    if sr <= 15:
        return 30
    elif sr <= 19:
        return 20
    elif sr <= 24:
        return 10
    else:
        return 0

# Function to calculate points based on the economy rate
def economy_points(econ):
    if econ <= 3:
        return 50
    elif econ <= 5:
        return 40
    elif econ <= 7:
        return 30
    else:
        return 0

# Function to calculate points based on the bowling average
def average_points(avg):
    if avg <= 20:
        return 30
    elif avg <= 30:
        return 20
    elif avg <= 40:
        return 10
    else:
        return 0

# Function to calculate points for 4-wicket hauls
def four_wicket_hauls_points(fwh):
    if fwh >= 4:
        return 30
    elif fwh >= 2:
        return 20
    elif fwh >= 1:
        return 10
    else:
        return 0

In [91]:
#applying points
bowler_score_df['strike_rate_points'] = bowler_score_df['strike_rate'].apply(strike_rate_points)
bowler_score_df['economy_points'] = bowler_score_df['economy'].apply(economy_points)
bowler_score_df['average_points'] = bowler_score_df['bowler_average'].apply(average_points)
bowler_score_df['four_wicket_hauls_points'] = bowler_score_df['4W_Per_Innings'].apply(four_wicket_hauls_points)

In [92]:
# Calculate total points for each bowler
bowler_score_df['total_points'] = (bowler_score_df['strike_rate_points'] +
                             bowler_score_df['economy_points'] +
                             bowler_score_df['average_points'] +
                             bowler_score_df['four_wicket_hauls_points'])

# Printing the final DataFrame with points calculated
print(bowler_score_df[['bowler_id', 'bowler', 'strike_rate', 'economy', 'bowler_average', '4W_Per_Innings', 'total_points']])

      bowler_id bowler  strike_rate    economy  bowler_average  \
0         34061  DT Cn    23.518519   9.490000       35.741481
1         41740  MC Hs    18.000000   5.900000       15.200000
2         49496  SJ Oe    16.645161   6.203043       17.193871
3         55299  PM Se    15.413043   8.097429       21.261667
4         62432  MM Ai    16.361111   7.826494       19.694769
...         ...    ...          ...        ...             ...
1506    9822322  Sv Dy          NaN   7.250000             NaN
1507    9822392  PR Vr     6.000000   2.330000        2.330000
1508    9822420  PS Pa    12.000000  17.000000       34.000000
1509    9822441   K Ta    12.000000  14.250000       28.500000
1510    9888584  NS Pa    12.000000  11.500000       23.000000

      4W_Per_Innings  total_points
0                NaN            20
1                NaN            80
2                3.0           100
3                1.0            50
4                1.0            60
...              ...           ...
1506             NaN             0
1507             NaN           110
1508             NaN            40
1509             NaN            50
1510             NaN            50

[1511 rows x 7 columns]

CONVERTING THIS POINTS SHEET FOR ALL BOWLERS INTO EXCEL

In [93]:
bowler_score_df.to_excel('bowler_totalpoints.xlsx', index=False)

Now before selecting bowlers for our team we will be seeing their performance score based on cummulative wickets,conistency and recency.

In [94]:
bowler['match_dt'] = pd.to_datetime(bowler['match_dt'], errors='coerce')

# Ensure wickets column is numeric
bowler['wicket_count'] = pd.to_numeric(bowler['wicket_count'], errors='coerce').fillna(0)

In [95]:
cumulative_wickets = bowler.groupby('bowler_id')['wicket_count'].sum().reset_index()
cumulative_wickets.columns = ['bowler_id', 'total_wickets']

In [96]:
min_wickets =cumulative_wickets['total_wickets'].min()
max_wickets = cumulative_wickets['total_wickets'].max()

In [97]:
cumulative_wickets['normalized_wickets'] = 1 + ((cumulative_wickets['total_wickets'] - min_wickets) * (100 - 1) / (max_wickets - min_wickets))

In [98]:
cumulative_wickets

      bowler_id  total_wickets  normalized_wickets
0         34061             27           16.274286
1         41740              5            3.828571
2         49496             31           18.537143
3         55299             46           27.022857
4         62432             72           41.731429
...         ...            ...                 ...
1506    9822322              0            1.000000
1507    9822392              3            2.697143
1508    9822420              1            1.565714
1509    9822441              2            2.131429
1510    9888584              1            1.565714

[1511 rows x 3 columns]

In [99]:
bowler_data = cumulative_wickets.merge(
    bowler[['bowler_id','wicket_count','runs', 'match_dt']],
    on='bowler_id',
    how='left'
)

Consistency based on standard deviation of wickets

In [100]:
bowler_std = bowler_data.groupby('bowler_id')['wicket_count'].std().reset_index()

In [101]:
bowler_std.columns = ['bowler_id', 'std']

In [102]:
bowler_std['inverse_std'] = bowler_std['std'].apply(lambda x: 1 / x if x > 1e-8 else np.nan)  # Use np.nan instead of np.inf for near-zero std

In [103]:
bowler_std.rename(columns={'inverse_std': 'consistency'}, inplace=True)

In [104]:
bowler_std

      bowler_id       std  consistency
0         34061  0.776776     1.287372
1         41740  0.971825     1.028992
2         49496  1.368765     0.730586
3         55299  1.157366     0.864031
4         62432  0.950591     1.051977
...         ...       ...          ...
1506    9822322  0.000000          NaN
1507    9822392       NaN          NaN
1508    9822420       NaN          NaN
1509    9822441       NaN          NaN
1510    9888584       NaN          NaN

[1511 rows x 3 columns]

In [105]:
min_consistency = bowler_std['consistency'].min()
max_consistency = bowler_std['consistency'].max()

In [106]:
bowler_std['normalized_consistency'] = 1 + ((bowler_std['consistency'] - min_consistency) * (100 - 1) / (max_consistency - min_consistency))

print(bowler_std)

      bowler_id       std  consistency  normalized_consistency
0         34061  0.776776     1.287372               34.082235
1         41740  0.971825     1.028992               24.998130
2         49496  1.368765     0.730586               14.506802
3         55299  1.157366     0.864031               19.198464
4         62432  0.950591     1.051977               25.806268
...         ...       ...          ...                     ...
1506    9822322  0.000000          NaN                     NaN
1507    9822392       NaN          NaN                     NaN
1508    9822420       NaN          NaN                     NaN
1509    9822441       NaN          NaN                     NaN
1510    9888584       NaN          NaN                     NaN

[1511 rows x 4 columns]

In [107]:
#calculating recency

In [108]:
def calculate_recency(group):
    group = group.sort_values('match_dt')
    decay_rate = 0.1
    # Ensure 'match_dt' is datetime and calculate time difference in days
    group['match_dt'] = pd.to_datetime(group['match_dt'])
    time_diff = (group['match_dt'].max() - group['match_dt']).dt.days
    weights = np.exp(-decay_rate * time_diff)
    return np.average(group['wicket_count'], weights=weights)

bowler_recency = bowler_data.groupby('bowler_id').apply(calculate_recency).reset_index(name='recency')

In [109]:
min_recency = bowler_recency['recency'].min()
max_recency = bowler_recency['recency'].max()

In [110]:
bowler_recency['normalized_recency'] = 1 + ((bowler_recency['recency'] - min_recency) * (100 - 1) / (max_recency - min_recency))

print(bowler_recency)

      bowler_id       recency  normalized_recency
0         34061  3.575711e-01            8.591697
1         41740  9.804233e-32            1.000000
2         49496  1.000000e+00           22.231294
3         55299  8.698915e-01           19.468923
4         62432  4.501641e-01           10.557567
...         ...           ...                 ...
1506    9822322  0.000000e+00            1.000000
1507    9822392  3.000000e+00           64.693883
1508    9822420  1.000000e+00           22.231294
1509    9822441  2.000000e+00           43.462589
1510    9888584  1.000000e+00           22.231294

[1511 rows x 3 columns]

In [111]:
bowler_performance = cumulative_wickets.merge(
    bowler_std, on='bowler_id'
).merge(
    bowler_recency, on='bowler_id'
)

In [112]:
bowler_performance

,bowler_id,total_wickets,normalized_wickets,std,consistency,normalized_consistency,recency,normalized_recency
0,34061,27,16.274286,0.776776,1.287372,34.082235,3.575711e-01,8.591697
1,41740,5,3.828571,0.971825,1.028992,24.998130,9.804233e-32,1.000000
2,49496,31,18.537143,1.368765,0.730586,14.506802,1.000000e+00,22.231294
3,55299,46,27.022857,1.157366,0.864031,19.198464,8.698915e-01,19.468923
4,62432,72,41.731429,0.950591,1.051977,25.806268,4.501641e-01,10.557567
...,...,...,...,...,...,...,...,...
1506,9822322,0,1.000000,0.000000,NaN,NaN,0.000000e+00,1.000000
1507,9822392,3,2.697143,NaN,NaN,NaN,3.000000e+00,64.693883
1508,9822420,1,1.565714,NaN,NaN,NaN,1.000000e+00,22.231294
1509,9822441,2,2.131429,NaN,NaN,NaN,2.000000e+00,43.462589
1510,9888584,1,1.565714,NaN,NaN,NaN,1.000000e+00,22.231294

In [113]:
#now we will give different weights to different attributes
weight_wickets = 0.4
weight_consistency = 0.3
weight_recency = 0.3

In [114]:
# Calculate bowler_performance
bowler_performance['performance_score'] = (bowler_performance['normalized_wickets'] * weight_wickets +
                     bowler_performance['normalized_consistency'] * weight_consistency +
                     bowler_performance['normalized_recency'] * weight_recency)

print(bowler_performance)

      bowler_id  total_wickets  normalized_wickets       std  consistency  \
0         34061             27           16.274286  0.776776     1.287372
1         41740              5            3.828571  0.971825     1.028992
2         49496             31           18.537143  1.368765     0.730586
3         55299             46           27.022857  1.157366     0.864031
4         62432             72           41.731429  0.950591     1.051977
...         ...            ...                 ...       ...          ...
1506    9822322              0            1.000000  0.000000          NaN
1507    9822392              3            2.697143       NaN          NaN
1508    9822420              1            1.565714       NaN          NaN
1509    9822441              2            2.131429       NaN          NaN
1510    9888584              1            1.565714       NaN          NaN

      normalized_consistency       recency  normalized_recency  \
0                  34.082235  3.575711e-01            8.591697
1                  24.998130  9.804233e-32            1.000000
2                  14.506802  1.000000e+00           22.231294
3                  19.198464  8.698915e-01           19.468923
4                  25.806268  4.501641e-01           10.557567
...                      ...           ...                 ...
1506                     NaN  0.000000e+00            1.000000
1507                     NaN  3.000000e+00           64.693883
1508                     NaN  1.000000e+00           22.231294
1509                     NaN  2.000000e+00           43.462589
1510                     NaN  1.000000e+00           22.231294

      performance_score
0             19.311894
1              9.330867
2             18.436286
3             22.409359
4             27.601722
...                 ...
1506                NaN
1507                NaN
1508                NaN
1509                NaN
1510                NaN

[1511 rows x 9 columns]

Now we have bowler performance score and bowler points we will merge them and add them to get best performers overall

In [115]:
merged_bowler = pd.merge(bowler_score_df, bowler_performance, on='bowler_id')

In [116]:
merged_bowler.columns

Index(['bowler_id', 'strike_rate', 'bowler', 'economy', 'bowler_average',
       '4W_Per_Innings', 'strike_rate_points', 'economy_points',
       'average_points', 'four_wicket_hauls_points', 'total_points',
       'total_wickets', 'normalized_wickets', 'std', 'consistency',
       'normalized_consistency', 'recency', 'normalized_recency',
       'performance_score'],
      dtype='object')

In [117]:
merged_bowler['final_score']=merged_bowler['total_points']+merged_bowler['performance_score']

In [118]:
final_bowler=merged_bowler[['bowler_id','bowler','total_wickets','strike_rate','economy','bowler_average','4W_Per_Innings','strike_rate_points', 'economy_points',
       'average_points', 'four_wicket_hauls_points','total_points','performance_score','final_score']]

In [119]:
final_bowler

,bowler_id,bowler,total_wickets,strike_rate,economy,bowler_average,4W_Per_Innings,strike_rate_points,economy_points,average_points,four_wicket_hauls_points,total_points,performance_score,final_score
0,34061,DT Cn,27,23.518519,9.490000,35.741481,NaN,10,0,10,0,20,19.311894,39.311894
1,41740,MC Hs,5,18.000000,5.900000,15.200000,NaN,20,30,30,0,80,9.330867,89.330867
2,49496,SJ Oe,31,16.645161,6.203043,17.193871,3.0,20,30,30,20,100,18.436286,118.436286
3,55299,PM Se,46,15.413043,8.097429,21.261667,1.0,20,0,20,10,50,22.409359,72.409359
4,62432,MM Ai,72,16.361111,7.826494,19.694769,1.0,20,0,30,10,60,27.601722,87.601722
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1506,9822322,Sv Dy,0,NaN,7.250000,NaN,NaN,0,0,0,0,0,NaN,NaN
1507,9822392,PR Vr,3,6.000000,2.330000,2.330000,NaN,30,50,30,0,110,NaN,NaN
1508,9822420,PS Pa,1,12.000000,17.000000,34.000000,NaN,30,0,10,0,40,NaN,NaN
1509,9822441,K Ta,2,12.000000,14.250000,28.500000,NaN,30,0,20,0,50,NaN,NaN
1510,9888584,NS Pa,1,12.000000,11.500000,23.000000,NaN,30,0,20,0,50,NaN,NaN

In [120]:
final_bowler.to_excel('final_bowler_scores.xlsx', index=False)

now we will be filtering out the bowlers eligible for our team by putting the filter of cummulative wickets more than 10

In [121]:
bowler_cummulative_wickets = bowler.groupby('bowler_id').agg(
    cumulative_wickets=pd.NamedAgg(column='wicket_count', aggfunc='sum')
).reset_index()

In [122]:
bowler_above10 = bowler_cummulative_wickets[bowler_cummulative_wickets['cumulative_wickets'] > 10]

print(bowler_above10)

      bowler_id  cumulative_wickets
0         34061                  27
2         49496                  31
3         55299                  46
4         62432                  72
6         65183                  16
...         ...                 ...
1378    8833075                  21
1381    8845850                  32
1390    8907338                  47
1408    8986193                  22
1492    9455557                  15

[483 rows x 2 columns]

In [123]:
bowlerover10 = pd.merge(bowler_above10,final_bowler, on='bowler_id')

In [124]:
bowlerover10

,bowler_id,cumulative_wickets,bowler,total_wickets,strike_rate,economy,bowler_average,4W_Per_Innings,strike_rate_points,economy_points,average_points,four_wicket_hauls_points,total_points,performance_score,final_score
0,34061,27,DT Cn,27,23.518519,9.490000,35.741481,NaN,10,0,10,0,20,19.311894,39.311894
1,49496,31,SJ Oe,31,16.645161,6.203043,17.193871,3.0,20,30,30,20,100,18.436286,118.436286
2,55299,46,PM Se,46,15.413043,8.097429,21.261667,1.0,20,0,20,10,50,22.409359,72.409359
3,62432,72,MM Ai,72,16.361111,7.826494,19.694769,1.0,20,0,30,10,60,27.601722,87.601722
4,65183,16,TT Bn,16,11.812500,9.090000,17.500000,1.0,30,0,30,10,70,35.021377,105.021377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,8833075,21,JA Tr,21,10.714286,6.221818,11.380635,NaN,30,30,30,0,90,18.936344,108.936344
479,8845850,32,Rn Ad,32,19.937500,8.374194,27.062188,1.0,10,0,20,10,40,19.135272,59.135272
480,8907338,47,Zn Kn,47,17.808511,8.232439,24.276631,1.0,20,0,20,10,50,26.622844,76.622844
481,8986193,22,Ih,22,12.863636,7.282308,15.362500,2.0,30,0,30,20,80,11.560776,91.560776
482,9455557,15,Sh Sa,15,12.800000,6.536667,12.799333,2.0,30,30,30,20,110,27.176230,137.176230

Sorting over10 based on performance score first and then on total points.later we will find the common between the two so we can get bowlers with better total points as well as performance score.

In [125]:
b=bowlerover10.sort_values(by='performance_score', ascending=False).head(4)
print(b)

     bowler_id  cumulative_wickets bowler  total_wickets  strike_rate  \
455    8131255                 118  Hs Rf            118    17.398305
333    5554254                 175  Rd Kn            175    17.011429
85     2282125                  79   B Kr             79    19.278481
192    3519011                  76  MJ Sr             76    19.960526

      economy  bowler_average  4W_Per_Innings  strike_rate_points  \
455  8.230213       23.830212             2.0                  20
333  6.815938       19.160076             6.0                  20
85   7.247917       23.543987             5.0                  10
192  6.692174       21.987632             2.0                  10

     economy_points  average_points  four_wicket_hauls_points  total_points  \
455               0              20                        20            60
333              30              30                        30           110
85                0              20                        30            60
192              30              20                        20            80

     performance_score  final_score
455          50.953440   110.953440
333          46.347226   156.347226
85           41.806654   101.806654
192          41.451505   121.451505

In [126]:
b.to_excel('top_sortedbowler.xlsx', index=False)

In [127]:
bowlerover10.to_excel('over10wicketsbawler.xlsx', index=False)

From the above excels we will be able to figure out the bowlers and batsman for our team based on final scores

NOW FILTERING FOR WICKETKEEPER

In [128]:
batsman.columns

Index(['match id', 'batsman', 'batsman_id', 'batsman_dob', 'batsman_details',
       'is_batsman_captain', 'is_batsman_keeper', 'inning', 'runs',
       'balls_faced', 'over_faced_first', 'wicket kind', 'out_by_bowler',
       'out_by_fielder', 'bowler_id', 'bowler_dob', 'bowler_details',
       'is_bowler_keeper', 'is_bowler_captain', 'strike_rate', 'Fours',
       'Sixes', 'match_dt', 'ingestion_timestamp'],
      dtype='object')

In [129]:
batsman_keeper = batsman.groupby('batsman_id').agg(
    keeper_count=pd.NamedAgg(column='is_batsman_keeper', aggfunc='sum')
).reset_index()

In [130]:
keeper_filtered = batsman_keeper[batsman_keeper['keeper_count'] >2 ]

In [131]:
print(keeper_filtered)

      batsman_id  keeper_count
27        150093            39
46        196580            27
50        210328            48
51        211658             4
72        287209            17
...          ...           ...
1954     8942828             3
1976     9009356             3
1996     9059000             5
2003     9103996             3
2026     9346861             3

[162 rows x 2 columns]

Now we can merge it with the batsman final score sheet to get scores for them also

In [132]:
keepers = pd.merge(keeper_filtered,final_batsman, on='batsman_id', how='inner')

In [133]:
keepers

,batsman_id,keeper_count,batsman,total_runs,average_runs,centuries,half_centuries,strike_rate,strike_rate_points,average_points,centuries_points,half_centuries_points,performance_score,total_points,final_score
0,150093,39,JA Sn,506,12.974359,0.0,2.0,115.135128,40,5,0,5,10.790569,50,60.790569
1,196580,27,MS Di,338,12.518519,0.0,1.0,126.612593,40,5,0,5,5.467018,50,55.467018
2,210328,48,KD Kk,980,16.610169,0.0,2.0,137.973559,40,5,0,5,14.459161,50,64.459161
3,211658,4,U Kl,140,35.000000,0.0,1.0,84.737500,30,10,0,5,10.063329,45,55.063329
4,287209,17,Kn Al,414,23.000000,0.0,3.0,112.958889,40,5,0,10,12.986307,55,67.986307
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,8942828,3,Ak Pl,28,9.333333,0.0,0.0,97.643333,30,5,0,0,2.770157,35,37.770157
158,9009356,3,At Pu,64,21.333333,0.0,0.0,118.750000,40,5,0,0,6.242894,45,51.242894
159,9059000,5,A Sa,86,17.200000,0.0,1.0,61.298000,0,5,0,5,3.809325,10,13.809325
160,9103996,3,TK Ps,17,5.666667,0.0,0.0,44.443333,0,5,0,0,2.222854,5,7.222854
161,9346861,3,AP Rn,45,15.000000,0.0,0.0,97.060000,30,5,0,0,2.938595,35,37.938595

In [134]:
c=keepers.sort_values(by='final_score', ascending=False).head()
print(c)

    batsman_id  keeper_count  batsman  total_runs  average_runs  centuries  \
29     2263736            84    Md Rn        4031     43.815217        2.0
27     2162782            61    JC Br        3498     36.061856        6.0
94     4635658            46    JP Is        1796     28.507937        3.0
39     2654014            90  Q de Kk        2693     29.593407        2.0
95     4685568            63    PD St        2525     24.047619        1.0

    half_centuries  strike_rate  strike_rate_points  average_points  \
29            38.0   115.673261                  40              20
27            26.0   123.307835                  40              10
94            10.0   124.756984                  40               5
39            20.0   121.033846                  40               5
95            14.0   132.002952                  40               5

    centuries_points  half_centuries_points  performance_score  total_points  \
29                20                     20          61.356321           100
27                30                     20          50.054794           100
94                30                     20          32.088733            95
39                20                     20          36.808932            85
95                10                     20          46.750240            75

    final_score
29   161.356321
27   150.054794
94   127.088733
39   121.808932
95   121.750240

In [135]:
c.to_excel('top_keepers.xlsx', index=False)

In [136]:
keepers.to_excel('keepersmorethan2.xlsx', index=False)

NEXT WE HAVE TO FILTER ALLROUNDERS AND THEN DETERMINE THEIR SCORES.

In [137]:
batsman.columns

Index(['match id', 'batsman', 'batsman_id', 'batsman_dob', 'batsman_details',
       'is_batsman_captain', 'is_batsman_keeper', 'inning', 'runs',
       'balls_faced', 'over_faced_first', 'wicket kind', 'out_by_bowler',
       'out_by_fielder', 'bowler_id', 'bowler_dob', 'bowler_details',
       'is_bowler_keeper', 'is_bowler_captain', 'strike_rate', 'Fours',
       'Sixes', 'match_dt', 'ingestion_timestamp'],
      dtype='object')

In [138]:
bowler.columns

Index(['match id', 'bowler', 'bowler_id', 'bowler_dob', 'bowler_details',
       'is_bowler_captain', 'is_bowler_keeper', 'inning', 'runs',
       'wicket_count', 'balls_bowled', 'economy', 'maiden', 'dots', 'Fours',
       'Sixes', 'wides', 'noballs', 'match_dt', 'ingestion_timestamp',
       'runs_conceded'],
      dtype='object')

first we will be putting the all rounder criteria then we will check if that player meets the criteria atleast 2 times

In [139]:
batsman['meets_batting_criteria'] = batsman['runs'] > 10
bowler['meets_bowling_criteria'] =bowler['wicket_count'] >= 1

In [140]:
# Creating a Dataframe for batsman criteria
batsman_df = batsman[['match id', 'batsman_id', 'meets_batting_criteria']].rename(columns={'batsman_id': 'player_id'})

In [141]:
# Creating a Dataframe for bowler criteria
bowler_df = bowler[['match id', 'bowler_id', 'meets_bowling_criteria']].rename(columns={'bowler_id': 'player_id'})

In [142]:
# Merging the two DataFrames on match_id and player_id
combined_df = pd.merge(batsman_df, bowler_df, on=['match id', 'player_id'], how='outer').fillna(False)

In [143]:
# Combining the criteria to check if it meets bowling abd batsman criteria
combined_df['meets_criteria'] = combined_df['meets_batting_criteria'] & combined_df['meets_bowling_criteria']

In [144]:
criteria_counts = combined_df.groupby('player_id')['meets_criteria'].sum().reset_index()

In [145]:
all_rounders = criteria_counts[criteria_counts['meets_criteria'] >= 2]
print(all_rounders)

      player_id  meets_criteria
1         34061               5
4         41740               2
10        62432              26
12        65183               3
13        74087               9
...         ...             ...
1981    8489816               3
2027    8725562               2
2055    8779896               2
2070    8845850               4
2207    9346854               2

[340 rows x 2 columns]

In [146]:
final_bowler.columns

Index(['bowler_id', 'bowler', 'total_wickets', 'strike_rate', 'economy',
       'bowler_average', '4W_Per_Innings', 'strike_rate_points',
       'economy_points', 'average_points', 'four_wicket_hauls_points',
       'total_points', 'performance_score', 'final_score'],
      dtype='object')

In [147]:
final_batsman.columns

Index(['batsman_id', 'batsman', 'total_runs', 'average_runs', 'centuries',
       'half_centuries', 'strike_rate', 'strike_rate_points', 'average_points',
       'centuries_points', 'half_centuries_points', 'performance_score',
       'total_points', 'final_score'],
      dtype='object')

Changing player_id to batsman_id to merge it with final_batsman sheet

In [148]:
df1=all_rounders.rename(columns={'player_id': 'batsman_id'})

In [149]:
all_rounder_batsman = pd.merge(df1,final_batsman, on='batsman_id', how='inner')

In [150]:
all_rounder_batsman

,batsman_id,meets_criteria,batsman,total_runs,average_runs,centuries,half_centuries,strike_rate,strike_rate_points,average_points,centuries_points,half_centuries_points,performance_score,total_points,final_score
0,34061,5,DT Cn,729,14.019231,0.0,2.0,119.160577,40,5,0,5,11.161964,50,61.161964
1,41740,2,MC Hs,976,23.804878,0.0,6.0,116.654878,40,5,0,20,13.975117,65,78.975117
2,62432,26,MM Ai,1911,21.965517,0.0,7.0,121.130345,40,5,0,20,29.020687,65,94.020687
3,65183,3,TT Bn,109,15.571429,0.0,0.0,129.745714,40,5,0,0,7.064019,45,52.064019
4,74087,9,RS Ba,1338,20.584615,0.0,10.0,103.259385,40,5,0,20,18.619661,65,83.619661
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,8489816,3,Ai Nr,125,15.625000,0.0,0.0,101.447500,40,5,0,0,4.930159,45,49.930159
336,8725562,2,L Kn Sa,79,9.875000,0.0,0.0,83.932500,30,5,0,0,3.386039,35,38.386039
337,8779896,2,An Hm Kn,101,7.214286,0.0,0.0,137.925714,40,5,0,0,4.095919,45,49.095919
338,8845850,4,Rn Ad,160,8.000000,0.0,0.0,88.179500,30,5,0,0,2.964822,35,37.964822
339,9346854,2,Al Al,63,21.000000,0.0,0.0,144.973333,40,5,0,0,4.941635,45,49.941635

Changing batsman_id to merge it with final_bowler sheet

In [151]:
df2 = all_rounder_batsman.rename(columns={'batsman_id': 'bowler_id'})

In [152]:
all_rounder_bowler_batsman = pd.merge(df2, final_bowler, on='bowler_id', how='inner')

In [153]:
all_rounder_bowler_batsman

,bowler_id,meets_criteria,batsman,total_runs,average_runs,centuries,half_centuries,strike_rate_x,strike_rate_points_x,average_points_x,...,economy,bowler_average,4W_Per_Innings,strike_rate_points_y,economy_points,average_points_y,four_wicket_hauls_points,total_points_y,performance_score_y,final_score_y
0,34061,5,DT Cn,729,14.019231,0.0,2.0,119.160577,40,5,...,9.490000,35.741481,NaN,10,0,10,0,20,19.311894,39.311894
1,41740,2,MC Hs,976,23.804878,0.0,6.0,116.654878,40,5,...,5.900000,15.200000,NaN,20,30,30,0,80,9.330867,89.330867
2,62432,26,MM Ai,1911,21.965517,0.0,7.0,121.130345,40,5,...,7.826494,19.694769,1.0,20,0,30,10,60,27.601722,87.601722
3,65183,3,TT Bn,109,15.571429,0.0,0.0,129.745714,40,5,...,9.090000,17.500000,1.0,30,0,30,10,70,35.021377,105.021377
4,74087,9,RS Ba,1338,20.584615,0.0,10.0,103.259385,40,5,...,8.110000,26.332944,1.0,10,0,20,10,40,34.793589,74.793589
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,8489816,3,Ai Nr,125,15.625000,0.0,0.0,101.447500,40,5,...,8.082727,37.622500,NaN,0,0,10,0,10,12.668363,22.668363
336,8725562,2,L Kn Sa,79,9.875000,0.0,0.0,83.932500,30,5,...,8.295000,32.598000,NaN,0,0,10,0,10,20.673771,30.673771
337,8779896,2,An Hm Kn,101,7.214286,0.0,0.0,137.925714,40,5,...,9.050000,20.750000,NaN,30,0,20,0,50,17.623572,67.623572
338,8845850,4,Rn Ad,160,8.000000,0.0,0.0,88.179500,30,5,...,8.374194,27.062188,1.0,10,0,20,10,40,19.135272,59.135272
339,9346854,2,Al Al,63,21.000000,0.0,0.0,144.973333,40,5,...,8.416667,38.500000,NaN,0,0,10,0,10,22.436826,32.436826

Adding performance,total points and final score of batsman and bolwer criteria to get their score for all rounder criteria

In [154]:
all_rounder_bowler_batsman['total_performance_score'] = all_rounder_bowler_batsman['performance_score_x'] + all_rounder_bowler_batsman['performance_score_y']
all_rounder_bowler_batsman['total_total_points'] = all_rounder_bowler_batsman['total_points_x'] + all_rounder_bowler_batsman['total_points_y']
all_rounder_bowler_batsman['total_final_score'] = all_rounder_bowler_batsman['final_score_x'] + all_rounder_bowler_batsman['final_score_y']

In [155]:
all_rounder_bowler_batsman

,bowler_id,meets_criteria,batsman,total_runs,average_runs,centuries,half_centuries,strike_rate_x,strike_rate_points_x,average_points_x,...,strike_rate_points_y,economy_points,average_points_y,four_wicket_hauls_points,total_points_y,performance_score_y,final_score_y,total_performance_score,total_total_points,total_final_score
0,34061,5,DT Cn,729,14.019231,0.0,2.0,119.160577,40,5,...,10,0,10,0,20,19.311894,39.311894,30.473858,70,100.473858
1,41740,2,MC Hs,976,23.804878,0.0,6.0,116.654878,40,5,...,20,30,30,0,80,9.330867,89.330867,23.305985,145,168.305985
2,62432,26,MM Ai,1911,21.965517,0.0,7.0,121.130345,40,5,...,20,0,30,10,60,27.601722,87.601722,56.622409,125,181.622409
3,65183,3,TT Bn,109,15.571429,0.0,0.0,129.745714,40,5,...,30,0,30,10,70,35.021377,105.021377,42.085396,115,157.085396
4,74087,9,RS Ba,1338,20.584615,0.0,10.0,103.259385,40,5,...,10,0,20,10,40,34.793589,74.793589,53.413250,105,158.413250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,8489816,3,Ai Nr,125,15.625000,0.0,0.0,101.447500,40,5,...,0,0,10,0,10,12.668363,22.668363,17.598523,55,72.598523
336,8725562,2,L Kn Sa,79,9.875000,0.0,0.0,83.932500,30,5,...,0,0,10,0,10,20.673771,30.673771,24.059810,45,69.059810
337,8779896,2,An Hm Kn,101,7.214286,0.0,0.0,137.925714,40,5,...,30,0,20,0,50,17.623572,67.623572,21.719491,95,116.719491
338,8845850,4,Rn Ad,160,8.000000,0.0,0.0,88.179500,30,5,...,10,0,20,10,40,19.135272,59.135272,22.100094,75,97.100094
339,9346854,2,Al Al,63,21.000000,0.0,0.0,144.973333,40,5,...,0,0,10,0,10,22.436826,32.436826,27.378461,55,82.378461

In [156]:
all_rounder_bowler_batsman = all_rounder_bowler_batsman.rename(columns={'bowler_id': 'player_id'})

In [157]:
all_rounder_bowler_batsman

,player_id,meets_criteria,batsman,total_runs,average_runs,centuries,half_centuries,strike_rate_x,strike_rate_points_x,average_points_x,...,strike_rate_points_y,economy_points,average_points_y,four_wicket_hauls_points,total_points_y,performance_score_y,final_score_y,total_performance_score,total_total_points,total_final_score
0,34061,5,DT Cn,729,14.019231,0.0,2.0,119.160577,40,5,...,10,0,10,0,20,19.311894,39.311894,30.473858,70,100.473858
1,41740,2,MC Hs,976,23.804878,0.0,6.0,116.654878,40,5,...,20,30,30,0,80,9.330867,89.330867,23.305985,145,168.305985
2,62432,26,MM Ai,1911,21.965517,0.0,7.0,121.130345,40,5,...,20,0,30,10,60,27.601722,87.601722,56.622409,125,181.622409
3,65183,3,TT Bn,109,15.571429,0.0,0.0,129.745714,40,5,...,30,0,30,10,70,35.021377,105.021377,42.085396,115,157.085396
4,74087,9,RS Ba,1338,20.584615,0.0,10.0,103.259385,40,5,...,10,0,20,10,40,34.793589,74.793589,53.413250,105,158.413250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,8489816,3,Ai Nr,125,15.625000,0.0,0.0,101.447500,40,5,...,0,0,10,0,10,12.668363,22.668363,17.598523,55,72.598523
336,8725562,2,L Kn Sa,79,9.875000,0.0,0.0,83.932500,30,5,...,0,0,10,0,10,20.673771,30.673771,24.059810,45,69.059810
337,8779896,2,An Hm Kn,101,7.214286,0.0,0.0,137.925714,40,5,...,30,0,20,0,50,17.623572,67.623572,21.719491,95,116.719491
338,8845850,4,Rn Ad,160,8.000000,0.0,0.0,88.179500,30,5,...,10,0,20,10,40,19.135272,59.135272,22.100094,75,97.100094
339,9346854,2,Al Al,63,21.000000,0.0,0.0,144.973333,40,5,...,0,0,10,0,10,22.436826,32.436826,27.378461,55,82.378461

In [158]:
print(all_rounder_bowler_batsman[['player_id', 'bowler', 'batsman', 'total_performance_score', 'total_total_points', 'total_final_score']])

     player_id    bowler   batsman  total_performance_score  \
0        34061     DT Cn     DT Cn                30.473858
1        41740     MC Hs     MC Hs                23.305985
2        62432     MM Ai     MM Ai                56.622409
3        65183     TT Bn     TT Bn                42.085396
4        74087     RS Ba     RS Ba                53.413250
..         ...       ...       ...                      ...
335    8489816     Ai Nr     Ai Nr                17.598523
336    8725562   L Kn Sa   L Kn Sa                24.059810
337    8779896  An Hm Kn  An Hm Kn                21.719491
338    8845850     Rn Ad     Rn Ad                22.100094
339    9346854     Al Al     Al Al                27.378461

     total_total_points  total_final_score
0                    70         100.473858
1                   145         168.305985
2                   125         181.622409
3                   115         157.085396
4                   105         158.413250
..                  ...                ...
335                  55          72.598523
336                  45          69.059810
337                  95         116.719491
338                  75          97.100094
339                  55          82.378461

[340 rows x 6 columns]

In [159]:
all_rounder_bowler_batsman.to_excel('allrounderspoints.xlsx', index=False)

In [160]:
d=all_rounder_bowler_batsman.sort_values(by='total_performance_score', ascending=False).head()
print(d)

     player_id  meets_criteria batsman  total_runs  average_runs  centuries  \
70     2275195              22   GJ Ml        2480     26.105263        3.0
110    2827327              22   LS Le        2678     27.050505        1.0
86     2486896              22   JS Nm        1495     15.412371        0.0
48     1934099              25   AD Rl        1526     18.166667        0.0
256    5554254              23   Rd Kn         795      9.464286        0.0

     half_centuries  strike_rate_x  strike_rate_points_x  average_points_x  \
70             14.0     126.458211                    40                 5
110            16.0     140.219192                    40                 5
86              3.0     117.007835                    40                 5
48              6.0     143.655952                    40                 5
256             1.0     118.920833                    40                 5

     ...  strike_rate_points_y  economy_points  average_points_y  \
70   ...                     0               0                10
110  ...                    10               0                20
86   ...                    20               0                20
48   ...                    20               0                20
256  ...                    20              30                30

     four_wicket_hauls_points  total_points_y performance_score_y  \
70                          0              10           35.410878
110                         0              30           29.389619
86                         10              50           36.308492
48                         20              60           36.737515
256                        30             110           46.347226

     final_score_y  total_performance_score  total_total_points  \
70       45.410878                72.228552                 105
110      59.389619                71.136289                 105
86       86.308492                62.012771                 105
48       96.737515                61.348875                 125
256     156.347226                58.327486                 160

     total_final_score
70          177.228552
110         176.136289
86          167.012771
48          186.348875
256         218.327486

[5 rows x 31 columns]

In [161]:
d.to_excel('topallrounderspoints.xlsx', index=False)

Now we have all the sorted excels containg the data we need and now we can select the best 11 players for our team.

In [162]:
#to make sure no values are repeated while selecting we can make a set
selected_ids = set()

In [163]:
# Select top wicketkeeper
top_keeper = keepers.nlargest(1, ['performance_score'])[['batsman_id', 'total_points', 'performance_score']]
top_keeper.rename(columns={'batsman_id': 'player_id'}, inplace=True)
top_keeper['role'] = 'wicket-keeper'
selected_ids.update(top_keeper['player_id'])

In [164]:
# Exclude already selected players from other DataFrames
all_rounder_bowler_batsman = all_rounder_bowler_batsman[~all_rounder_bowler_batsman['player_id'].isin(selected_ids)]
batsmanover100 = batsmanover100[~batsmanover100['batsman_id'].isin(selected_ids)]
over10 = bowlerover10[~bowlerover10['bowler_id'].isin(selected_ids)]

In [165]:
# Select top 3 allrounders
top_allrounders = all_rounder_bowler_batsman.sort_values(by='total_performance_score', ascending=False).nlargest(3, ['total_performance_score'])[['player_id', 'total_total_points', 'total_performance_score']]
top_allrounders.rename(columns={'total_total_points': 'total_points', 'total_performance_score': 'performance_score'}, inplace=True)
top_allrounders['role'] = 'allrounder'
selected_ids.update(top_allrounders['player_id'])

In [166]:
# Select top 3 batsmen
top_batsmen = batsmanover100.nlargest(3, ['performance_score'])[['batsman_id', 'total_points', 'performance_score']]
top_batsmen.rename(columns={'batsman_id': 'player_id'}, inplace=True)
top_batsmen['role'] = 'batsman'
selected_ids.update(top_batsmen['player_id'])

In [167]:
# Exclude already selected players from bowlers DataFrame
over10 = over10[~over10['bowler_id'].isin(selected_ids)]

I am choosing to have 4 bawlers ,as analysed above i noticed that all rounders have a better batsman score and thus to balance the team one extra bowler is taken instead of a batsman

In [168]:
# Select top 4 bowlers
top_bowlers = bowlerover10.nlargest(4, ['performance_score'])[['bowler_id', 'total_points', 'performance_score']]
top_bowlers.rename(columns={'bowler_id': 'player_id'}, inplace=True)
top_bowlers['role'] = 'bowler'
selected_ids.update(top_bowlers['player_id'])

In [169]:
# Combine selected players
final_team = pd.concat([top_batsmen, top_bowlers, top_allrounders, top_keeper])

In [170]:
final_team

     player_id  total_points  performance_score           role
164    2162782           100          50.054794        batsman
482    4685568            75          46.750240        batsman
139    2076192            80          45.186521        batsman
455    8131255            60          50.953440         bowler
333    5554254           110          46.347226         bowler
85     2282125            60          41.806654         bowler
192    3519011            80          41.451505         bowler
70     2275195           105          72.228552     allrounder
110    2827327           105          71.136289     allrounder
86     2486896           105          62.012771     allrounder
29     2263736           100          61.356321  wicket-keeper

In [171]:
final_team.to_excel('finalteam.xlsx', index=False)